### PR TITLE
Update gem.png

### PR DESCRIPTION
**Pull request by Studio-Mojo**
Updating GEM Icon with this correctly sizes gem.png

Thank you!

### CODE REVIEW

**Comment by yan-wl** [comment]
Please upload the image on an image hosting website and provide us with the link instead.

**Comment by Studio-Mojo** [comment]
> Please upload the image on an image hosting website and provide us with the link instead.

https://i.imgur.com/3K3ihwC.png

Thank you yan-wl!

**Comment by Studio-Mojo** [comment]
Did the Gem Icon get loaded properly with the above link that was requested?  As I don’t see any change on CoinHall Listing.

**Comment by yan-wl** [comment]
> > Please upload the image on an image hosting website and provide us with the link instead.
> 
> https://i.imgur.com/3K3ihwC.png
> 
> Thank you yan-wl!

This link gives `Error not found`

**Comment by Studio-Mojo** [comment]
> > > Please upload the image on an image hosting website and provide us with the link instead.
> > 
> > 
> > https://i.imgur.com/3K3ihwC.png
> > Thank you yan-wl!
> 
> This link gives `Error not found`

Ok I think I got it worked out:  Try this link:  https://i.imgur.com/H40xhCs.png

**Comment by Studio-Mojo** [comment]
> > > Please upload the image on an image hosting website and provide us with the link instead.
> > 
> > 
> > https://i.imgur.com/3K3ihwC.png
> > Thank you yan-wl!
> 
> This link gives `Error not found`

I think I got it worked out now, thank you for pointing this out.

https://i.imgur.com/H40xhCs.png

**Comment by Studio-Mojo** [comment]
@yan-wl  Here is the updated Link that works for Updating GEM Icon.

https://i.imgur.com/H40xhCs.png

**Comment by yan-wl** [comment]
> @yan-wl Here is the updated Link that works for Updating GEM Icon.
> 
> Please see that this link gets used for the update. Thank you!
> 
> https://i.imgur.com/H40xhCs.png

Link still does not work

**Comment by Studio-Mojo** [comment]
> > @yan-wl Here is the updated Link that works for Updating GEM Icon.
> > Please see that this link gets used for the update. Thank you!
> > https://i.imgur.com/H40xhCs.png
> 
> Link still does not work

I opened a request with Imgur as that is where the issue lies.  Once they fit it, this link should work from what I am seeing.  
Screenshot 2024-06-05 at 11 00 33 PM

**Comment by Studio-Mojo** [comment]
@yan-wl _ Good Morning, a team community member has secured the GEM Logo and here is the link

https://bafkreigfw66cljelcuurfbwx3ccrp7cpwuga6boygmo22xr74oaady4dxq.kirud.link/

Please let me know if this is acceptable.  Thank you!

**Comment by Studio-Mojo** [comment]
> Please upload the image on an image hosting website and provide us with the link instead.

GEM Icon is properly hosted here:
https://bafkreigfw66cljelcuurfbwx3ccrp7cpwuga6boygmo22xr74oaady4dxq.kirud.link/

Please confirm it can be updated - Thank you!

**Pull request closed without merging**
