### PR TITLE
Add seizophrenia

### PR DESCRIPTION
**Pull request by SiWarlock**

### CODE REVIEW

**Comment by ITO1201** [comment]
The pool.json update automatically..you don't need to add it

**Comment by SiWarlock** [comment]
> The pool.json update automatically..you don't need to add it

Yeah, I keep forgetting that. I fixed it, but now I am getting the error I was getting before with "did you forget to run format.sh?"

Everything should be correct now.

**Comment by ITO1201** [comment]
close the pull request first and create another one without changing pool.json

**Comment by yusufaine** [comment]
not needed, will manually update, thanks for helping @ITO1201

**Pull request merged**
